### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 18811386351** [streamer-AP/UCAS_Paper_2023#1]
你好，我在中国科技云的latex模板共享中下载了本论文模板（https://www.cstcloud.cn/resources/456） ,然后使用中国科技云overleaf服务编译出现了报错
![Uploading overleaf报错.png…]()

**Comment by streamer-AP** [comment]
报错图片看不到呢，重发一下试试

**Comment by 18811386351** [comment]
![overleaferrorsfixed](https://github.com/streamer-AP/UCAS_Paper_2023/assets/57722505/a5db2e2a-f354-4342-80b2-17fe0e8e3328)

**Comment by streamer-AP** [comment]
没用科技云的试过，这是在overleaf上的配置，尝试调成一样的试试 
![微信图片_20231114170140](https://github.com/streamer-AP/UCAS_Paper_2023/assets/37429186/6ff465da-b468-4990-af12-cc86f67da3b4)

**Comment by 18811386351** [comment]
> 没用科技云的试过，这是在overleaf上的配置，尝试调成一样的试试 ![微信图片_20231114170140](https://user-images.githubusercontent.com/37429186/282719863-6ff465da-b468-4990-af12-cc86f67da3b4.png)

配置调好，解决了，谢谢
