### ISSUE TITLE
如何给参考文献自定义分类且不标号？

### ISSUE THREAD

**Issue by Hermiterexakm** [streamer-AP/UCAS_Paper_2023#2]
新版的规定针对某些专业有特殊要求，其中一个就是要按照一手文献和研究文献分语种进行分类，请问应当使用什么代码实现？
已经尝试过：\printbibliography[title={Book references},type=book] \printbibliography[title={Article references},type=article] \printbibliography[title={Other references}, nottype=article, nottype=book] %依照书籍、期刊等分类
但这样设置后参考文献处还是会有标号，如何去掉标号？
下面这个不知道能不能实现
\addbibresource{references.bib}
\addbibresource{other.bib}

**Comment by streamer-AP** [comment]
如果取消标号可以使用author-year 标注。
