### ISSUE TITLE
为什么前面每一页都会空一页呀

### ISSUE THREAD

**Issue by Karma1628** [streamer-AP/UCAS_Paper_2023#4]

**Comment by streamer-AP** [comment]
每一页都空一页这个现象我没见过。但有些时候空白页是为了满足学校的装订要求。

**Comment by Karma1628** [comment]
好像就是正文之前的有空白页

这个是最新的要求，您看下

学位论文是研究生在掌握已有的科学知识的基础上，运用科学思维和一定的科学方法、技术与工具，面向特定的科学领域所存在的科学问题，开展创新性研究而产生的科学研究成果。
学位论文是研究生科研工作成果的集中体现，是评判学位申请者学术水平、授予其学位的主要依据，是科研领域重要的文献资料。撰写学位论文是对研究生科学研究能力的基本训练，是研究生学业与研究成效的基本检验，也是科研与创新能力的重要体现。
为提高研究生学位论文的撰写质量，促进学位论文在内容和格式上的规范化，参照《学位论文编写规则》（GB/T 7713.1—2006）、《信息与文献 参考文献著录规则》（GB/T 7714—2015）和《学术出版规范 期刊学术不端行为界定》（CY/T 174—2019）等国家有关标准，特制定本指导意见（2021年修订）。各学科群学位评定分委员会（以下简称各学科群分会）可结合本学科领域的特点，参考本指导意见，制订符合本学科领域特点与要求的学位论文撰写具体要求。
本指导意见从2023年冬季批次开始实施。
一、组成及要求
学位论文一般由以下几个部分组成：封面、原创性声明及授权使用声明、摘要、目录、符号说明（若有）、正文、参考文献、附录（若有）、致谢、作者简历及攻读学位期间发表的学术论文与其他相关学术成果等。
（一） 封面 
一律采用中国科学院大学规定的统一中英文封面（见样张1和样张2），封面包含内容如下： 
1.	密级 
涉密或延迟公开论文必须在论文封面标注密级，同时注明保密年限。公开论文不标注密级，可删除此行。
2.	论文题目 
应简明扼要地概括和反映整个论文的核心内容，一般不宜超过25个汉字（符），英文题目一般不应超过150个字母，必要时可加副标题。题目中应尽量避免使用缩略词、首字母缩写词、字符、代号和公式等。
3.	作者姓名 
根据《中国人名汉语拼音字母拼写规则》（GB/T 28039—2011），英文封面中的姓和名分写，姓在前，名在后，姓名之间用空格分开。姓和名需写全拼，姓全大写，名首字母大写。外国留学生姓名书写顺序以护照格式为准，字母全部大写。
4.	指导教师 
需同时填写导师姓名、专业技术职务和工作单位。如果有多位导师（均需经培养单位批准，并在学籍系统备案），第一导师在前，第二导师等依次在后。学位论文在指导小组的指导下完成的，应注明指导小组成员相应信息。
5.	学位类别
包括学科门类（学术型）或专业学位类别以及学位级别。学科门类如理学、医学等，专业学位类别如应用统计、工商管理等。学位级别包括硕士、博士。
6.	学科专业
填写攻读学位的一级学科/二级学科或专业学位类别/领域全称，须与学籍信息一致，不可用简写。
7.	培养单位
填写就读研究所或学院、系全称，如中国科学院××研究所、中国科学院大学××学院。
8.	时间
填写论文提交学位授予单位的年月，使用阿拉伯数字标注。一般夏季申请学位的论文标注6月，冬季申请学位的论文标注12月。例如：2023年6月，2023年12月。
（二）原创性声明及授权使用声明
本部分内容提供统一的模版，具体内容见样张3，提交时作者和导师须亲笔签名。如遇导师无法签字时，培养单位应做出适当处理。
（三）摘要和关键词
论文摘要包括中文摘要和英文摘要（Abstract）两部分。论文摘要应概括地反映出本论文的主要内容，说明本论文的主要研究目的、内容、方法、结论。要突出本论文的创造性成果或新见解，不宜使用公式、图表、表格或其他插图材料，不标注引用文献。中文摘要的字数由各学科群分会根据本分会涉及学科专业的特点提出具体要求。英文摘要与中文摘要内容应保持一致。留学生用其他语种撰写学位论文时，应有详细的中文摘要，字数由各学科群分会具体制定，建议一般不少于5000字。
摘要最后注明本文的关键词（3～5个）。关键词是为了文献标引和检索工作，从论文中选取出来，用以表示全文主题内容信息的单词或术语。关键词以显著的字符另起一行并隔行排列于摘要下方，左顶格，中文关键词间用中文逗号隔开。英文关键词应与中文关键词对应，首字母应大写，用英文逗号隔开。
摘要应另起一页，与正文前的内容连续编页（用罗马字符）。
（四）目录 
目录应包括论文正文中的全部内容的标题，以及参考文献、附录（若有）和致谢等，不包括中英文摘要。目录页由论文的章、条、附录等序号、名称和页码组成。正文章节题名要求最多编到第三级标题，即×.×.×（如1.1.1）。一级标题顶格书写，二级标题缩进一个汉字符位置，三级标题缩进两个汉字符位置。论文中若有图表，应有图表目录，置于目录页之后，另页编排。图表目录应有序号、图题或表题和页码。
目录应另起一页，与正文前的内容连续编页（用罗马字符）。
（五）符号说明（若有）
如果论文中使用了大量的物理量符号、标志、缩略词、专门计量单位、自定义名词和术语等，应编写成注释说明汇集表。若上述符号等使用数量不多，可以不设此部分，但必须在论文中首次出现时加以说明。
论文中若有符号说明，应置于目录之后、正文之前，另起一页，与正文前的内容连续编页（用罗马字符）。

**Comment by streamer-AP** [comment]
正文之前每一页都有空白页吗 ？如果是那应该是你某些地方搞错了。参考提供的PDF ，没发现这个问题。可以截图看一下

另按照学校要求：
论文正文须由另页右页（奇数页）开始，用阿拉伯数字连续编码，一直到全文最后。正文内部新章节无须另页右页（奇数页）开始。

**Comment by streamer-AP** [comment]
论文封面使用中国科学院大学统一的封面格式。学位论文用A4标准纸（210 mm×297 mm）打印、印刷或复印，按顺序装订成册。自中文摘要起双面印刷，之前部分单面印刷。中文摘要、英文摘要、目录、论文正文、参考文献、附录、致谢、作者简历及攻读学位期间发表的学术论文与其他相关学术成果等，**均须由另页右页（奇数页）开始**。论文必须用线装或热胶装订，不使用钉子装订。封面用纸一般为150克花纹纸（需保证论文封面印刷质量，字迹清晰、不脱落），博士学位论文封面颜色为红色，硕士学位论文封面颜色为蓝色。

**Comment by Karma1628** [comment]
> 正文之前每一页都有空白页吗 ？如果是那应该是你某些地方搞错了。参考提供的PDF ，没发现这个问题。可以截图看一下
> 
> 另按照学校要求： 论文正文须由另页右页（奇数页）开始，用阿拉伯数字连续编码，一直到全文最后。正文内部新章节无须另页右页（奇数页）开始。

是的，我发现了这个要求，之前疏忽了，麻烦您了，感谢您的耐心答疑。
